import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';

import hero from '../assets/images/hero.jpg';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className="">
        <div className="fixed h-screen w-screen overflow-hidden -z-10 ">
          <Image
            alt="Hero"
            src={hero}
            layout="fill"
            objectFit="cover"
            quality={80}
            priority={true}
            className="bg-gradient-to-b from-[#4847fa] to-[#615dfa]"
          />
        </div>
        <div className="container">
          <div className="grid-cols-8 grid-rows-2">
            <div className="col-span-2 row-span-1">signin</div>
            <div className="col-span-6 row-span-2">big box</div>
            <div className="col-span-2 row-span-1">register</div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
